export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
} as const;  

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <>
      {children}
    </>
  )
}
